app:
  name: Minecraft FRP Tool
  theme: auto
  version: 2.0.0
decrypt_key: clashman
frp:
  config_filename: config/frpc.ini
  ping_data_filename: config/ping_data.yaml
  thread_timeout: 3000
network:
  download_timeout: 5
  ping_timeout: 1000
  reserved_ports:
  - 80
  - 443
  - 3306
  - 8080
  - 25565
settings:
  auto_mapping: false
  dark_mode_override: true
  force_dark_mode: true
  last_server: 北京2
ui:
  ad_update_interval: 3000
  ping_update_interval: 3000
  window_height: 550
  window_width: 400
